CameraSonyConfig:
    camera_index: 1
    width: 1920
    height: 1080
    fps: 30
    rtsp_url: rtsp://localhost:8554/mystream
    snapshot_host: 0.0.0.0
    snapshot_port: 8001
    ffmpeg_path: D:\Driver\ffmpeg-2026-05-06-git-f2e5eff3ff-essentials_build\bin\ffmpeg.exe
    flip_horizontal: true
    snapshot_format: png
    snapshot_jpeg_quality: 95
    ffmpeg_cmd:
        - '{ffmpeg_path}'
        - -y
        - -f
        - rawvideo
        - -vcodec
        - rawvideo
        - -pix_fmt
        - bgr24
        - -s
        - '{actual_width}x{actual_height}'
        - -r
        - '{fps}'
        - -i
        - '-'
        - -c:v
        - libx264
        - -preset
        - ultrafast
        - -tune
        - zerolatency
        - -crf
        - '23'
        - -g
        - '{gop}'
        - -keyint_min
        - '{gop}'
        - -bf
        - '0'
        - -profile:v
        - baseline
        - -pix_fmt
        - yuv420p
        - -x264-params
        - nal-hrd=cbr:force-cfr=1
        - -f
        - rtsp
        - -rtsp_transport
        - tcp
        - -muxdelay
        - '0'
        - -muxpreload
        - '0'
        - -max_delay
        - '0'
        - -flush_packets
        - '1'
        - '{rtsp_url}'
