weights_path: D:\Camera\Weight\VRS_260828_yolo11n_320x320\weights\best.pt
class_name_filter: 0
imgsz: 320
port: 8191
save_images: true
saved_images_dir: D:\Camera\Dev\AutoBoardOffset_YOLO_2Mat\fiducial_detector\saved_images
